FROM ghcr.io/osgeo/gdal:ubuntu-small-3.9.0
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    postgresql-client curl jq unzip ca-certificates && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /project

